// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {email} from '../models';
import {task} from '../models';

export function AddOutlookAccounts(arg1:string):Promise<Record<string, any>>;

export function CancelUpdate():Promise<Record<string, any>>;

export function CheckLicense():Promise<Record<string, any>>;

export function CheckUpdate():Promise<Record<string, any>>;

export function ClearOutlookAccounts():Promise<Record<string, any>>;

export function DeleteOutlookAccount(arg1:string):Promise<Record<string, any>>;

export function DownloadUpdate():Promise<Record<string, any>>;

export function GetDataDir():Promise<string>;

export function GetDirectMailConfigs():Promise<Array<email.DirectMailConfig>>;

export function GetDuckDuckGoConfigs():Promise<Array<email.DuckDuckGoConfig>>;

export function GetLicenseInfo():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function GetMoeMailConfigs():Promise<Array<email.MoeMailConfig>>;

export function GetOutlookAccounts():Promise<Array<Record<string, any>>>;

export function GetOverview():Promise<Record<string, any>>;

export function GetProxy():Promise<string>;

export function GetResultOutputDir():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function GetTEmailConfigs():Promise<Array<email.TEmailConfig>>;

export function GetTaskStatus():Promise<Record<string, any>>;

export function ImportOutlookFile(arg1:string):Promise<Record<string, any>>;

export function LogoutLicense():Promise<Record<string, any>>;

export function OpenURL(arg1:string):Promise<void>;

export function ResetDataDir():Promise<Record<string, any>>;

export function ResetProxy():Promise<Record<string, any>>;

export function ResetResultOutputDir():Promise<Record<string, any>>;

export function SaveDirectMailConfigs(arg1:string):Promise<Record<string, any>>;

export function SaveDuckDuckGoConfigs(arg1:string):Promise<Record<string, any>>;

export function SaveMoeMailConfigs(arg1:string):Promise<Record<string, any>>;

export function SaveTEmailConfigs(arg1:string):Promise<Record<string, any>>;

export function SelectDirectory():Promise<string>;

export function SelectOutlookFile():Promise<string>;

export function SetDataDir(arg1:string):Promise<Record<string, any>>;

export function SetProxy(arg1:string):Promise<Record<string, any>>;

export function SetResultOutputDir(arg1:string):Promise<Record<string, any>>;

export function StartTask(arg1:task.StartTaskRequest):Promise<Record<string, any>>;

export function StopTask():Promise<Record<string, any>>;

export function TestDirectMailConnection(arg1:string):Promise<Record<string, any>>;

export function TestDuckDuckGoConnection(arg1:string):Promise<Record<string, any>>;

export function TestMoeMailConnection(arg1:string):Promise<Record<string, any>>;

export function TestTEmailConnection(arg1:string):Promise<Record<string, any>>;

export function VerifyLicense(arg1:string):Promise<Record<string, any>>;
